version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=theaterDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Folosim un volum pentru a persista datele

  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/theaterDB
    volumes:
      - ./public:/app/public  # Montează volumul pentru a accesa pozele

volumes:
  mongo-data:  # Definim volumul pentru date
